config/routes.rb
Rails.application.routes.draw do
  get 'rooms/show'
  resources :pasts
  resources :rooms, only: %i[show]

  get "posts/index"         => "posts#index"
  get 'posts/new'           => "posts#new"
  get "posts/:id"           => "posts#show"
  get "posts/:id/past_mondai"=>"posts#past_mondai"
  get "posts/:id/note"      => "posts#note"
  get "posts/:id/handout"   => "posts#handout"
  get "posts/:id/task"      => "posts#task"
  get "posts/:id/another"   => "posts#another"
  post"posts/:id/create"    => "posts#create"
  post"posts/:id/evaluate"  => "posts#evaluate"
  post"posts/:id/like"      => "posts#like"
  post"posts/:id/bad"       => "posts#bad"

  get "subjects/new"        => "subjects#new"
  get "subjects/:id"        => "subjects#show"
  get "subjects/:id/edit"   => "subjects#edit"
  post "subjects/:id/create"=> "subjects#create"
  post 'subjects/create'    => "subjects#create"
  post "subjects/:id/update"=> "subjects#update"

  get "teachers/new"        => "teachers#new"
  get "teachers/:id"        => "teachers#show"
  get "teachers/:id/edit"   => "teachers#edit"
  post "teachers/:id/create"=> "teachers#create"
  post 'teachers/create'    => "teachers#create"
  post "teachers/:id/update"=> "teachers#update"

  get "courses/new"         => "courses#new"
  get "courses/:id"         => "courses#show"
  get "courses/:id/edit"    => "courses#edit"
  post 'courses/create'     => "courses#create"
  post "courses/:id/update" => "courses#update"

  get "users/index"         => "users#index"
  get "users/:id"           => "users#show"
  get "users/:id/edit"      => "users#edit"
  post "users/create"       => "users#create"
  post "users/search"       => "users#search"
  post "users/:id/update"   => "users#update"

  post "login"              => "users#login"
  post "logout"             => "users#logout"
  get "login"               => "users#login_form"
  get "signup"              => "users#new"

  get "/"                   => "home#top"
  get "about"               => "home#about"
  post "home/search"        => "home#search"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  has_one :room,dependent: :destroy

  validates :name,    {presence: true}
  validates :user_id, {presence: true}

  def teachers
    return Teacher.where(course_id: self.id)
  end

end

app/models/message.rb
class Message < ApplicationRecord
  validates :content, presence: true
  # createの後にコミットする { MessageBroadcastJobのperformを遅延実行 引数はself }
  after_create_commit { MessageBroadcastJob.perform_later self }
  has_many :notifications, dependent: :destroy

  belongs_to :user,optional: true
  belongs_to :room
end

app/models/notification.rb
class Notification < ApplicationRecord
  default_scope -> { order(created_at: :desc) }

  belongs_to :message, optional: true
  belongs_to :visitor, class_name: 'User', foreign_key: 'visitor_id', optional: true
  belongs_to :visited, class_name: 'User', foreign_key: 'visited_id', optional: true
end

app/models/past.rb
class Past < ApplicationRecord
  has_many_attached :images

  validates :name,    {presence: true}
  validates :subject_id, {presence: true}
  validates :post_at, {presence:true}
  validates :level,   {presence:true}
  validates :when,    {presence:true}

end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :iem,optional: true
  mount_uploader :image,ImageUploader
end

app/models/post.rb
class Post < ApplicationRecord
  validates :content, {presence: true, length: {maximum: 140}}
  validates :subject_id, {presence: true}
  validates :level,      {presence: true}

  def subjects
    return Subject.find_by(id:self.subject_id)
  end


end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages,dependent: :destroy
  belongs_to :subject,optional: true
  belongs_to :course, optional: true
end

app/models/subject.rb
require 'bigdecimal'

class Subject < ApplicationRecord
  has_many :rooms,dependent: :destroy
  validates :name,    {presence: true}
  validates :teacher_id, {presence: true}

  def user
    @c = Teacher.find_by(id:self.teacher_id)
    @c = Course.find_by(id:@c.course_id)
    return User.find_by(id:@c.user_id)
  end

  def teachers
    return Teacher.find_by(id:self.teacher_id)
  end

  def contents
    @p = Post.where(subject_id:self.id).order(like:"DESC").first
    if @p
      return @p
    else
      return Post.new(content:"")
    end
  end


  def floor_class
    return BigDecimal(Subject.find_by(id:self.id).level.to_s).floor(2).to_f # 1.24
  end


end

app/models/teacher.rb
require 'bigdecimal'

class Teacher < ApplicationRecord
  validates :name,    {presence: true}
  validates :course_id, {presence: true}

    def user
      @c = Course.find_by(id:self.course_id)
      return User.find_by(id:@c.user_id)
    end

    def subjects
      return Subject.where(teacher_id: self.id)
    end

    def course_name_name
      @c = Course.find_by(id:self.course_id)
      if @c
        return @c
      else
        return Course.new
      end
    end

    def contents
      @a = Subject.find_by(teacher_id:self.id)
      return Post.find_by(subject_id:@a.id)
    end

    def floor_class
      @a = Subject.where(teacher_id:self.id).sum(:level)
      @c = Subject.where(teacher_id:self.id).count
      @a = @a/@c
      return BigDecimal(@a.to_s).floor(2).to_f # 1.24
    end


end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password

  has_many :messages
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy

  validates :name, {presence: true,uniqueness:true}


  def courses
    return Course.where(user_id: self.id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user, {only: [:index, :edit, :update]}
  before_action :ensure_correct_user, {only: [:edit, :update,]}
  before_action :course_id_delete_form_session
  before_action :teacher_id_delete_form_session
  before_action :subject_id_delete_form_session


  def index
    @users = User.all
  end

  def show
    @user = User.find_by(id: params[:id])
    session[:now_id] = params[:id]
  end

  def search
    @user = User.find_by(name:params[:name])
    if @user
      redirect_to("/users/#{@user.id}")
    else
      redirect_to("/users/index")
    end
  end


  def new
    @user = User.new
  end

  def create
    @user = User.new(
      name: params[:name],
      image_name: "default_user.jpg",
      password: params[:password]
    )
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "ユーザー登録が完了しました"
      redirect_to("/users/#{@user.id}")
    else
      render("users/new")
    end
  end

  def edit
    @user = User.find_by(id: params[:id])
  end

  def update
    @user = User.find_by(id: params[:id])
    @user.name = params[:name]

    if params[:image]
      @user.image_name = "#{@user.id}.jpg"
      image = params[:image]
      File.binwrite("public/user_images/#{@user.image_name}", image.read)
    end

    if @user.save
      flash[:notice] = "ユーザー情報を編集しました"
      redirect_to("/users/#{@user.id}")
    else
      render("users/edit")
    end
  end

  def login_form
  end

  def login
    # メールアドレスのみを用いて、ユーザーを取得するように書き換えてください
    @user = User.find_by(name: params[:name])
    # if文の条件を&&とauthenticateメソッドを用いて書き換えてください
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      session[:now_id]  = @user.id
      flash[:notice] = "ログインしました"
      redirect_to("/users/#{@user.id}")
    else
      @error_message = "メールアドレスまたはパスワードが間違っています"
      @name = params[:name]
      @password = params[:password]
      render("users/login_form")
    end
  end

  def logout
    session[:user_id] = nil
    session[:course_id] =nil
    session[:teacher_id] =nil
    session[:subject_id] = nil
    session[:now_id] =nil
    flash[:notice] = "ログアウトしました"
    redirect_to("/login")
  end


  def ensure_correct_user
    if @current_user.id != params[:id].to_i
      flash[:notice] = "権限がありません"
      redirect_to("/users/#{session[:user_id]}")
    end
  end

end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ims_helper.rb
module ImsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/mvs_helper.rb
module MvsHelper
end

app/helpers/pasts_helper.rb
module PastsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="main users-edit">
  <div class="container">
    <div class="form-heading">アカウント編集</div>
    <div class="form users-form">
      <div class="form-body">
        <% @user.errors.full_messages.each do |message| %>
          <div class="form-error">
            <%= message %>
          </div>
        <% end %>

        <!-- form_tagメソッドに「multipart: true」を追加してください -->
        <%= form_tag("/users/#{@user.id}/update", {multipart: true}) do %>
          <p>ユーザー名</p>
          <input name="name" value="<%= @user.name %>">
          <p>画像</p>
          <!-- 画像用のフォームを追加してください -->
          <input name="image" type="file">
          <input type="submit" value="保存">
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="main users-index">
  <div class="form-search">
  <div class="form2 users-form2">
    <div class="form-body2">
      <%= form_tag("/users/search") do %>
        <p style="color:black;font-size:14px;margin:0;text-align:center">学校名</p>
        <input name="name" value="">
        <input type="submit" value="検索">
      <% end %>
    </div>
  </div>
  </div>
  <div clas="user">
  <div class="container">
    <div class="form-heading">学校一覧</div>
    <% @users.each do |user| %>
      <div class="users-index-item">
        <div class="user-left">
          <img src="<%= "/user_images/#{user.image_name}" %>">
        </div>
        <div class="user-right22">
          <div class="post-user-name-users">
          <p><%= link_to(user.name, "/users/#{user.id}") %></p>
        </div>
        </div>
      </div>
    <% end %>
  </div>
  </div>
</div>

app/views/users/login_form.html.erb
<div class="main users-new">
  <div class="container">
    <div class="form-heading">ログイン</div>
    <div class="form users-form">
      <div class="form-body">
        <!-- 指定されたHTMLを貼り付けてください -->
        <% if @error_message %>
          <div class="form-error">
            <%= @error_message %>
          </div>
        <% end %>
        <%= form_tag("/login") do %>
          <p>学校名</p>
          <!-- value属性を追加してください -->
          <input name="name" value="<%= @name %>">
          <p>パスワード</p>
          <!-- value属性を追加してください -->
          <input type="password" name="password" value="<%= @password %>">
          <input type="submit" value="ログイン">
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="main users-new">
  <div class="container">
    <h1 class="form-heading">新規学校登録</h1>
    <div class="form users-form">
      <div class="form-body">
        <% @user.errors.full_messages.each do |message| %>
          <div class="form-error">
            <%= message %>
          </div>
        <% end %>

        <%= form_tag("/users/create") do %>
          <p>学校名</p>
          <input name="name" value="<%= @user.name %>">
          <p>パスワード</p>
          <!-- パスワード用のフォームを追加してください -->
          <input type="password" name="password" value="<%= @user.password %>">
          <input type="submit" value="新規登録">
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="main user-show">
  <div class="container">
    <div class="user">
      <img src="<%= "/user_images/#{@user.image_name}" %>">
      <h2><%= @user.name %></h2>
      <% if @current_user%>
        <% if @user.id == @current_user.id %>
          <%= link_to("編集", "/users/#{@user.id}/edit") %>
        <% end %>
      <% end %>
    </div>

    <!-- 指定されたコードを貼り付けてください -->
    <% @user.courses.each do |course| %>
      <div class="posts-index-item">
        <div class="post-left">
          <img src="<%= "/courses_images/#{course.image_name}" %>">
        </div>
        <div class="post-right">
          <div class="post-user-name-users">
            <%= link_to(course.name, "/courses/#{course.id}") %>
          </div>
        </div>
        <div class="aa">
          <%= link_to "チャットへ", room_path(course.room)%>
        </div>
      </div>
    <% end %>

  </div>
</div>